/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import controle.Carro;
import controle.HoraData;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import modelo.GerenciadorArquivo;

/**
 *
 * @author christian medeiros
 */
public class JFIEntradaVeic extends javax.swing.JInternalFrame {

    /**
     * Creates new form jfiEntradaVeic
     */
    public JFIEntradaVeic() {
        initComponents();
        this.setSize(1140, 340);
        HoraData hrdt = new HoraData();
        jlbldata.setText(hrdt.mostraData());
        atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jlblPlaca = new javax.swing.JLabel();
        jlblVeiculo = new javax.swing.JLabel();
        jlblModelo = new javax.swing.JLabel();
        jlblEntrada = new javax.swing.JLabel();
        jtxtPlaca = new javax.swing.JTextField();
        jtxtModelo = new javax.swing.JTextField();
        jtxtEntrada = new javax.swing.JTextField();
        jlblDataLabel = new javax.swing.JLabel();
        jlblHoraLabel = new javax.swing.JLabel();
        jbtnOK = new javax.swing.JButton();
        jbtnCancal = new javax.swing.JButton();
        jlbldata = new javax.swing.JLabel();
        jlblhora = new javax.swing.JLabel();
        jbtnVisualizar = new javax.swing.JButton();
        jbtnSaida = new javax.swing.JButton();
        jtxtPesquisa = new javax.swing.JTextField();
        jtxtSaida = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jcbVeiculo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstacionados = new javax.swing.JTable();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Entrada de Veículos");
        setPreferredSize(new java.awt.Dimension(1110, 373));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel1KeyPressed(evt);
            }
        });

        jlblPlaca.setText("Placa");

        jlblVeiculo.setText("Veículo");

        jlblModelo.setText("Modelo");

        jlblEntrada.setText("Hora Entrada");

        jtxtPlaca.setToolTipText("ABC1234");
        jtxtPlaca.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                testString(evt);
            }
        });
        jtxtPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPlacaActionPerformed(evt);
            }
        });
        jtxtPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPlacaKeyPressed(evt);
            }
        });

        jtxtEntrada.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtEntradaFocusGained(evt);
            }
        });
        jtxtEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEntradaActionPerformed(evt);
            }
        });

        jlblDataLabel.setText("Data");

        jlblHoraLabel.setText("Hora");

        jbtnOK.setText("OK");
        jbtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOKActionPerformed(evt);
            }
        });

        jbtnCancal.setText("Cancel");

        jbtnVisualizar.setText("Vis/Alterar");
        jbtnVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnVisualizarActionPerformed(evt);
            }
        });

        jbtnSaida.setForeground(java.awt.Color.red);
        jbtnSaida.setText("Saída");
        jbtnSaida.setEnabled(false);
        jbtnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaidaActionPerformed(evt);
            }
        });

        jtxtPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtPesquisaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtxtPesquisaFocusLost(evt);
            }
        });
        jtxtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtPesquisaKeyPressed(evt);
            }
        });

        jtxtSaida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtxtSaidaFocusGained(evt);
            }
        });

        jLabel1.setText("Hora Saída");

        jcbVeiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1 - Carro", "2 - Moto", "3 - Caminhonete" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jbtnSaida, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jbtnOK, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(jlblPlaca, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlblModelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtModelo, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtPlaca, javax.swing.GroupLayout.Alignment.LEADING))
                        .addComponent(jlblDataLabel)
                        .addComponent(jlblHoraLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jcbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtnVisualizar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jlblEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlblVeiculo)
                                .addComponent(jbtnCancal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlbldata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlblhora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jtxtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblPlaca)
                    .addComponent(jlblVeiculo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlblModelo)
                            .addComponent(jlblEntrada))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtSaida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblDataLabel)
                    .addComponent(jlbldata, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlblHoraLabel)
                    .addComponent(jlblhora, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOK)
                    .addComponent(jbtnCancal)
                    .addComponent(jbtnVisualizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSaida)
                    .addComponent(jtxtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTableEstacionados.setModel(new javax.swing.table.DefaultTableModel(
            controle.Carro.listarCarros(),
            new String [] {
                "Title 1","Title 2","Title 3","Title 4"
            }
        ));
        jTableEstacionados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableEstacionadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableEstacionados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void atualizaTabela() {
        jTableEstacionados.setModel(new DefaultTableModel(Carro.listarCarros(),
                new String[]{"Código", "Placa", "Tipo",
                    "Modelo", "Data", "H.Entrada", "H.Saída", "Tempo", "Valor"}));
        jTableEstacionados.setAutoResizeMode(jTableEstacionados.AUTO_RESIZE_OFF);
        DefaultTableModel dt = (DefaultTableModel) jTableEstacionados.getModel();
        dt.setNumRows(Carro.getSize());

    }
    private void jtxtPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPlacaActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Timer timer = new Timer(1000, new hora());
        timer.start();
        GerenciadorArquivo gerarq = new GerenciadorArquivo();
        gerarq.listar();
        atualizaTabela();

    }//GEN-LAST:event_formInternalFrameOpened

    private void jtxtPlacaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPlacaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {

        }

    }//GEN-LAST:event_jtxtPlacaKeyPressed

    private void jbtnVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnVisualizarActionPerformed
        //atualizaTabela();
        String placa = jtxtPlaca.getText();
        String hsaida = jtxtSaida.getText();
        GerenciadorArquivo gerarq = new GerenciadorArquivo();
        gerarq.alterar();
        atualizaTabela();
    }//GEN-LAST:event_jbtnVisualizarActionPerformed

    private void jbtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOKActionPerformed
        GerenciadorArquivo gerarq = new GerenciadorArquivo();
        String placa = jtxtPlaca.getText();
        String tipo = ""+(1+ jcbVeiculo.getSelectedIndex());
        //String tipo = jtxtVeiculo.getText();
        String modelo = jtxtModelo.getText();
        String data = jlbldata.getText();
        String hentrada = jtxtEntrada.getText();
        gerarq.escreve(placa, tipo, modelo, data, hentrada);
        atualizaTabela();
        jtxtPlaca.setText(null);
        //jtxtVeiculo.setText(null);
        jcbVeiculo.setSelectedIndex(0);
        jtxtModelo.setText(null);
        jtxtEntrada.setText(null);
        jtxtPlaca.requestFocus();

    }//GEN-LAST:event_jbtnOKActionPerformed

    private void testString(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_testString
        if (jtxtPlaca.getText().length() > 7) {
            JOptionPane.showMessageDialog(null, "Erro: " + jtxtPlaca.getText(), "Erro Placa", JOptionPane.WARNING_MESSAGE);
            jtxtPlaca.requestFocus();
        }
    }//GEN-LAST:event_testString

    private void jbtnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaidaActionPerformed
        jtxtSaida.setText(jlblhora.getText());
        GerenciadorArquivo gerarq = new GerenciadorArquivo();
        String hsaida = jtxtSaida.getText();
        gerarq.pesquisar(jtxtPesquisa.getText(), hsaida);
        jtxtPesquisa.setText(null);
        atualizaTabela();
        jtxtSaida.setText(null);
        jbtnSaida.setEnabled(false);
    }//GEN-LAST:event_jbtnSaidaActionPerformed

    private void jtxtEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEntradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEntradaActionPerformed

    private void jtxtEntradaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtEntradaFocusGained
        jtxtEntrada.setText(jlblhora.getText());
    }//GEN-LAST:event_jtxtEntradaFocusGained

    private void jtxtSaidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtSaidaFocusGained
        jtxtSaida.setText(jlblhora.getText());
    }//GEN-LAST:event_jtxtSaidaFocusGained

    private void jtxtPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPesquisaFocusGained
        jtxtSaida.setText(jlblhora.getText());
        jbtnSaida.setEnabled(true);
    }//GEN-LAST:event_jtxtPesquisaFocusGained

    private void jtxtPesquisaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtxtPesquisaFocusLost

    }//GEN-LAST:event_jtxtPesquisaFocusLost

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_formKeyPressed

    private void jPanel1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER && jtxtPesquisa.hasFocus()){
        jbtnSaida.doClick(); }
    }//GEN-LAST:event_jPanel1KeyPressed

    private void jtxtPesquisaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtPesquisaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        jbtnSaida.doClick(); 
        }
    }//GEN-LAST:event_jtxtPesquisaKeyPressed

    private void jTableEstacionadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableEstacionadosMouseClicked
        int selectedRowIndex = jTableEstacionados.getSelectedRow();
        int selectedColumnIndex = jTableEstacionados.getSelectedColumn();
        //Object selectedObject = (Object) jTableEstacionados.getModel().getValueAt(selectedRowIndex, selectedColumnIndex);
        Object selectedObject = (Object) jTableEstacionados.getModel().getValueAt(selectedRowIndex, 1);
        jtxtPesquisa.setText(""+selectedObject);
        jtxtSaida.setText(jlblhora.getText());
        jbtnSaida.setEnabled(true);
    }//GEN-LAST:event_jTableEstacionadosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstacionados;
    private javax.swing.JButton jbtnCancal;
    private javax.swing.JButton jbtnOK;
    private javax.swing.JButton jbtnSaida;
    private javax.swing.JButton jbtnVisualizar;
    private javax.swing.JComboBox jcbVeiculo;
    private javax.swing.JLabel jlblDataLabel;
    private javax.swing.JLabel jlblEntrada;
    private javax.swing.JLabel jlblHoraLabel;
    private javax.swing.JLabel jlblModelo;
    private javax.swing.JLabel jlblPlaca;
    private javax.swing.JLabel jlblVeiculo;
    private javax.swing.JLabel jlbldata;
    private javax.swing.JLabel jlblhora;
    private javax.swing.JTextField jtxtEntrada;
    private javax.swing.JTextField jtxtModelo;
    private javax.swing.JTextField jtxtPesquisa;
    private javax.swing.JTextField jtxtPlaca;
    private javax.swing.JTextField jtxtSaida;
    // End of variables declaration//GEN-END:variables

    class hora implements ActionListener {

    @Override
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        Calendar now = Calendar.getInstance();
        jlblhora.setText(String.format("%1$tH:%1$tM:%1$tS", now));
        //jtxtEntrada.setText(jlblhora.getText());
    }
}

}
