/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import controle.Carro;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import modelo.GerenciadorArquivo;



/**
 *
 * @author christian
 */
public class JFIVisualizar extends javax.swing.JInternalFrame {

    /**
     * Creates new form Visualizar
     */
    public JFIVisualizar() {
        initComponents();
        setLocation(0, 0);
        this.setSize(1110, 370);
        atualizaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEstacionados = new javax.swing.JTable();
        jbtnAtualiza = new javax.swing.JButton();

        setClosable(true);
        setTitle("Estacionados");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jTableEstacionados.setModel(new javax.swing.table.DefaultTableModel(
            controle.Carro.listarCarros(),
            new String [] {
                "Title 1","Title 2","Title 3","Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEstacionados);

        jbtnAtualiza.setText("Atualiza");
        jbtnAtualiza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnAtualizaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(456, Short.MAX_VALUE)
                .addComponent(jbtnAtualiza)
                .addGap(90, 90, 90))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtnAtualiza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void atualizaTabela() {
    jTableEstacionados.setModel(new DefaultTableModel(GerenciadorArquivo.listar(), new String[]{"Código","Placa","Tipo",
        "Modelo","Data","H.Entrada","H.Saída"}));
    jTableEstacionados.setAutoResizeMode(jTableEstacionados.AUTO_RESIZE_OFF);
    DefaultTableModel dt = (DefaultTableModel) jTableEstacionados.getModel();
    dt.setNumRows(Carro.getSize());
    
    }
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        //gerenciadorArquivo gerarq = new GerenciadorArquivo();
        GerenciadorArquivo gerarq = new GerenciadorArquivo();
        gerarq.listar();
        atualizaTabela();
    }//GEN-LAST:event_formInternalFrameOpened

    private void jbtnAtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnAtualizaActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_jbtnAtualizaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEstacionados;
    private javax.swing.JButton jbtnAtualiza;
    // End of variables declaration//GEN-END:variables

}
