
package visual;

import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.security.NoSuchAlgorithmException;
import javax.swing.JOptionPane;
import static modelo.VerificaSenha.verificaSenha;

/**
 *
 * @author christian
 */
public class JFLogin extends javax.swing.JFrame {

    /**
     * Creates new form jfLogin
     */
    public JFLogin() {

        //seuFrame.setLocationRelativeTo(null);  ou this
        initComponents();
        jtxtInvalidos.setVisible(false);
        this.setTitle("Parking - Identificação de Entrada");
        jtxtUsuario.setText("suporte");
        jlblAlerta.setVisible(false);
        if (Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK) == true) {
            jlblAlerta.setVisible(true);
        }
        //com.sun.awt.AWTUtilities.setWindowOpacity(this, 0.5f);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlblUsuario = new javax.swing.JLabel();
        jlblSenha = new javax.swing.JLabel();
        jtxtUsuario = new javax.swing.JTextField();
        jpwdSenha = new javax.swing.JPasswordField();
        jbtnEntrar = new javax.swing.JButton();
        jlblAlerta = new javax.swing.JLabel();
        jbtnCancelar = new javax.swing.JButton();
        jtxtInvalidos = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(400, 300));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });
        getContentPane().setLayout(null);

        jlblUsuario.setText("Usuário:");
        getContentPane().add(jlblUsuario);
        jlblUsuario.setBounds(30, 90, 56, 17);

        jlblSenha.setText("Senha:");
        getContentPane().add(jlblSenha);
        jlblSenha.setBounds(30, 150, 47, 17);

        jtxtUsuario.setToolTipText("Nome do Usuário");
        jtxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxtUsuarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtUsuarioKeyReleased(evt);
            }
        });
        getContentPane().add(jtxtUsuario);
        jtxtUsuario.setBounds(110, 80, 230, 27);

        jpwdSenha.setToolTipText("Palavra chave/senha");
        jpwdSenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jpwdSenhaKeyPressed(evt);
            }
        });
        getContentPane().add(jpwdSenha);
        jpwdSenha.setBounds(110, 140, 230, 27);

        jbtnEntrar.setText("Entrar");
        jbtnEntrar.setMaximumSize(new java.awt.Dimension(75, 29));
        jbtnEntrar.setMinimumSize(new java.awt.Dimension(75, 29));
        jbtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEntrarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnEntrar);
        jbtnEntrar.setBounds(106, 190, 110, 29);

        jlblAlerta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/alerta.png"))); // NOI18N
        jlblAlerta.setToolTipText("Caps Lock Ligado");
        jlblAlerta.setFocusable(false);
        getContentPane().add(jlblAlerta);
        jlblAlerta.setBounds(350, 70, 40, 40);

        jbtnCancelar.setText("Cancelar");
        jbtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jbtnCancelar);
        jbtnCancelar.setBounds(230, 190, 110, 29);

        jtxtInvalidos.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jtxtInvalidos.setForeground(java.awt.Color.red);
        jtxtInvalidos.setText("Usuário/Senha inválido");
        jtxtInvalidos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jtxtInvalidos);
        jtxtInvalidos.setBounds(150, 60, 170, 17);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/car-09-2.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 400, 300);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCancelarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jbtnCancelarActionPerformed

    private void jbtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEntrarActionPerformed
        String passText = new String(jpwdSenha.getPassword());
        String comparaSenha=null;
        try {
        comparaSenha = verificaSenha(passText);
        } catch (NoSuchAlgorithmException e){}
        //if (comparaSenha.equals("698dc19d489c4e4db73e28a713eab07b") && jtxtUsuario.getText().equalsIgnoreCase("teste")){
        if (passText.equals("") && jtxtUsuario.getText().equalsIgnoreCase("suporte")){
            // kevin 9d5e3ecdeb4cdb7acfd63075ae46672
            // teste 698dc19d489c4e4db73e28a713eab07b
            // admin 21232f297a57a5a743894a0e4a801fc3
            // luzzardi 40e0f0e2936c99fb18db2730ce4a0ef8
            new JFPrincipal().setVisible(true);
            this.dispose();
            
        } else {
            Toolkit.getDefaultToolkit().beep();
            jtxtInvalidos.setVisible(true);
            //JOptionPane.showMessageDialog(null, "Usuário/Senha inválido", "Erro", JOptionPane.ERROR_MESSAGE);
            jtxtUsuario.requestFocus();
            limparCampos();
        }
    }//GEN-LAST:event_jbtnEntrarActionPerformed

    private void jpwdSenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpwdSenhaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jbtnEntrarActionPerformed(null);
        }
    }//GEN-LAST:event_jpwdSenhaKeyPressed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowOpened

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyPressed

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyTyped

    private void jtxtUsuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUsuarioKeyPressed
        // TODO add your handling code here:
        if (Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK) == true) {
            Toolkit.getDefaultToolkit().beep();
            jlblAlerta.setVisible(true);
        } else {
            Toolkit.getDefaultToolkit().beep();
            jlblAlerta.setVisible(false);
        }
    }//GEN-LAST:event_jtxtUsuarioKeyPressed

    private void jtxtUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtUsuarioKeyReleased
        // TODO add your handling code here:
        if (Toolkit.getDefaultToolkit().getLockingKeyState(KeyEvent.VK_CAPS_LOCK) == true) {
            Toolkit.getDefaultToolkit().beep();
            jlblAlerta.setVisible(true);
        } else {
            Toolkit.getDefaultToolkit().beep();
            jlblAlerta.setVisible(false);
        }
    }//GEN-LAST:event_jtxtUsuarioKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(final String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //jfLogin.setDefaultLookAndFeelDecorated(true);
                new JFLogin().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbtnCancelar;
    private javax.swing.JButton jbtnEntrar;
    private javax.swing.JLabel jlblAlerta;
    private javax.swing.JLabel jlblSenha;
    private javax.swing.JLabel jlblUsuario;
    private javax.swing.JPasswordField jpwdSenha;
    private javax.swing.JLabel jtxtInvalidos;
    private javax.swing.JTextField jtxtUsuario;
    // End of variables declaration//GEN-END:variables

    private void limparCampos() {
        jtxtUsuario.setText(null);
        jpwdSenha.setText(null);
        jtxtUsuario.requestFocus();
    }

}
