/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visual;

import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.File;
import java.net.URI;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import modelo.GerenciadorArquivo;
import modelo.ImprimirRecibo;

/**
 *
 * @author christian
 */
public class JFPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form jfPrincipal
     */
    public JFPrincipal() {
        this.setLocationRelativeTo(this);
        initComponents();
        this.setTitle("Parking Sistema de Controle de Estacionamento 10/2015");
        setExtendedState(MAXIMIZED_BOTH);
        jbtnEntrada.setVerticalTextPosition(SwingConstants.BOTTOM);
        jbtnRegistros.setVerticalTextPosition(SwingConstants.BOTTOM);
        jbtnCadastros.setVerticalTextPosition(SwingConstants.BOTTOM);
        jbtnCaixas.setVerticalTextPosition(SwingConstants.BOTTOM);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jbtnEntrada = new javax.swing.JButton();
        jbtnRegistros = new javax.swing.JButton();
        jbtnCadastros = new javax.swing.JButton();
        jbtnCaixas = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmitSistema = new javax.swing.JMenu();
        jmitEntrada = new javax.swing.JMenuItem();
        jmitEstacionados = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmitCaixa = new javax.swing.JMenuItem();
        jmitMensalista = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jmitConfig = new javax.swing.JMenu();
        jmitInfoSys = new javax.swing.JMenuItem();
        jmitConfiguracao = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jmitOutros = new javax.swing.JMenu();
        jmitAcessoWeb = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jmitSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpPrincipal.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jdpPrincipalComponentRemoved(evt);
            }
        });

        jbtnEntrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/create-ticket.png"))); // NOI18N
        jbtnEntrada.setText("Entrada");
        jbtnEntrada.setToolTipText("Entrada");
        jbtnEntrada.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEntradaActionPerformed(evt);
            }
        });

        jbtnRegistros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnRegistros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/openofficeorg-writer.png"))); // NOI18N
        jbtnRegistros.setText("Registro");
        jbtnRegistros.setToolTipText("Registro");
        jbtnRegistros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnRegistros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrosActionPerformed(evt);
            }
        });

        jbtnCadastros.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnCadastros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/clients.png"))); // NOI18N
        jbtnCadastros.setText("Cadastro");
        jbtnCadastros.setToolTipText("Cadastro");
        jbtnCadastros.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCadastros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCadastrosActionPerformed(evt);
            }
        });

        jbtnCaixas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jbtnCaixas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/visual/imagens/money_bag.png"))); // NOI18N
        jbtnCaixas.setText("Caixa");
        jbtnCaixas.setToolTipText("Caixa");
        jbtnCaixas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtnCaixas.setMaximumSize(new java.awt.Dimension(140, 140));
        jbtnCaixas.setMinimumSize(new java.awt.Dimension(140, 140));
        jbtnCaixas.setPreferredSize(new java.awt.Dimension(140, 140));
        jbtnCaixas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCaixasActionPerformed(evt);
            }
        });

        jmitSistema.setText("Sistema");

        jmitEntrada.setText("Entrada");
        jmitEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitEntradaActionPerformed(evt);
            }
        });
        jmitSistema.add(jmitEntrada);

        jmitEstacionados.setText("Estacionados");
        jmitEstacionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitEstacionadosActionPerformed(evt);
            }
        });
        jmitSistema.add(jmitEstacionados);
        jmitSistema.add(jSeparator1);

        jmitCaixa.setText("Caixa");
        jmitCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitCaixaActionPerformed(evt);
            }
        });
        jmitSistema.add(jmitCaixa);

        jmitMensalista.setText("Mensalista");
        jmitSistema.add(jmitMensalista);

        jMenuItem7.setText("Ponto");
        jmitSistema.add(jMenuItem7);

        jMenuBar1.add(jmitSistema);

        jmitConfig.setText("Configuração");

        jmitInfoSys.setText("InfoSys");
        jmitInfoSys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitInfoSysActionPerformed(evt);
            }
        });
        jmitConfig.add(jmitInfoSys);

        jmitConfiguracao.setText("Configuração");
        jmitConfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitConfiguracaoActionPerformed(evt);
            }
        });
        jmitConfig.add(jmitConfiguracao);

        jMenuItem1.setText("Impressão");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jmitConfig.add(jMenuItem1);

        jMenuBar1.add(jmitConfig);

        jmitOutros.setText("Outros");

        jmitAcessoWeb.setText("Acesse nossa Página");
        jmitAcessoWeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitAcessoWebActionPerformed(evt);
            }
        });
        jmitOutros.add(jmitAcessoWeb);

        jMenuItem3.setText("Enviar E-mail");
        jmitOutros.add(jMenuItem3);

        jMenuBar1.add(jmitOutros);

        jmitSair.setText("Sair");
        jmitSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmitSairMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmitSairMouseClicked(evt);
            }
        });
        jmitSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jmitSair);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbtnEntrada)
                        .addComponent(jbtnRegistros))
                    .addComponent(jbtnCadastros)
                    .addComponent(jbtnCaixas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jdpPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jbtnCadastros, jbtnCaixas});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jbtnEntrada)
                .addGap(1, 1, 1)
                .addComponent(jbtnRegistros)
                .addGap(1, 1, 1)
                .addComponent(jbtnCadastros)
                .addGap(1, 1, 1)
                .addComponent(jbtnCaixas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jdpPrincipal)
        );

        setSize(new java.awt.Dimension(600, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmitSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitSairActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmitSairActionPerformed

    private void jmitAcessoWebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitAcessoWebActionPerformed
        try {
            Desktop desktop = java.awt.Desktop.getDesktop();
            URI oURL = new URI("http://www.google.com.br");
            desktop.browse(oURL);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jmitAcessoWebActionPerformed

    private void jmitEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitEntradaActionPerformed
        JFIEntradaVeic obj = new JFIEntradaVeic();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
        jbtnEntrada.setEnabled(false);
        jmitEntrada.setEnabled(false);
    }//GEN-LAST:event_jmitEntradaActionPerformed

    private void jmitEstacionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitEstacionadosActionPerformed
        JFIVisualizar obj = new JFIVisualizar();
        jdpPrincipal.add(obj);
        obj.setVisible(true);
    }//GEN-LAST:event_jmitEstacionadosActionPerformed

    private void jmitInfoSysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitInfoSysActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Pasta Sistema: " + System.getProperty("user.dir") + "\n"
                + "Sistema Operacional: " + System.getProperty("os.name") + "\n"
                + "Arquitetura: " + System.getProperty("os.arch") + "\n"
                + "Versão: " + System.getProperty("os.version") + "\n"
                + "Usuário: " + System.getProperty("user.name") + "\n"
                + "Java: " + System.getProperty("java.version"), "Informação", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jmitInfoSysActionPerformed

    private void jbtnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEntradaActionPerformed
        // impedir que abra mais de uma janela igual
        JFIEntradaVeic objEntradaVeic = new JFIEntradaVeic();
        jdpPrincipal.add(objEntradaVeic);
        objEntradaVeic.setVisible(true);
        jbtnEntrada.setEnabled(false);
        jmitEntrada.setEnabled(false);
    }//GEN-LAST:event_jbtnEntradaActionPerformed

    private void jmitConfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitConfiguracaoActionPerformed
        // TODO add your handling code here:
        JFIConfiguracao objConfiguracao = new JFIConfiguracao();
        jdpPrincipal.add(objConfiguracao);
        objConfiguracao.setVisible(true);
    }//GEN-LAST:event_jmitConfiguracaoActionPerformed

    private void jmitSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmitSairMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jmitSairMouseClicked

    private void jmitSairMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmitSairMousePressed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jmitSairMousePressed

    private void jdpPrincipalComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jdpPrincipalComponentRemoved
        if(evt.getChild().getY() == 0){
        jbtnEntrada.setEnabled(true);
        jmitEntrada.setEnabled(true);
        } else if (evt.getChild().getY() == 340){
        jbtnCaixas.setEnabled(true);
        jmitCaixa.setEnabled(true);
        }

    }//GEN-LAST:event_jdpPrincipalComponentRemoved

    private void jbtnRegistrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrosActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Acesso Negado", "Área Restrita", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jbtnRegistrosActionPerformed

    private void jbtnCadastrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCadastrosActionPerformed
        JOptionPane.showMessageDialog(null, "Acesso Negado", "Área Restrita", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jbtnCadastrosActionPerformed

    private void jbtnCaixasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCaixasActionPerformed
        //JOptionPane.showMessageDialog(null,"Acesso Negado","Área Restrita",JOptionPane.ERROR_MESSAGE);
        JFICaixas objCaixa = new JFICaixas();
        jdpPrincipal.add(objCaixa);
        objCaixa.setVisible(true);
        jbtnCaixas.setEnabled(false);
        jmitCaixa.setEnabled(false);
    }//GEN-LAST:event_jbtnCaixasActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        GerenciadorArquivo gerarq = new GerenciadorArquivo();
        gerarq.listar();
        ImprimirRecibo impRec = new ImprimirRecibo();
        JFileChooser arquivo = new JFileChooser();
        arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        arquivo.showDialog(null, null);
        File tmpArq = arquivo.getSelectedFile();
        impRec.imprime("" + tmpArq + "");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jmitCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitCaixaActionPerformed
        JFICaixas objCaixa = new JFICaixas();
        jdpPrincipal.add(objCaixa);
        objCaixa.setVisible(true);
        jbtnCaixas.setEnabled(false);
        jmitCaixa.setEnabled(false);
    }//GEN-LAST:event_jmitCaixaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JButton jbtnCadastros;
    private javax.swing.JButton jbtnCaixas;
    private javax.swing.JButton jbtnEntrada;
    private javax.swing.JButton jbtnRegistros;
    private javax.swing.JDesktopPane jdpPrincipal;
    private javax.swing.JMenuItem jmitAcessoWeb;
    private javax.swing.JMenuItem jmitCaixa;
    private javax.swing.JMenu jmitConfig;
    private javax.swing.JMenuItem jmitConfiguracao;
    private javax.swing.JMenuItem jmitEntrada;
    private javax.swing.JMenuItem jmitEstacionados;
    private javax.swing.JMenuItem jmitInfoSys;
    private javax.swing.JMenuItem jmitMensalista;
    private javax.swing.JMenu jmitOutros;
    private javax.swing.JMenu jmitSair;
    private javax.swing.JMenu jmitSistema;
    // End of variables declaration//GEN-END:variables

}
